name: 'Versioning Action'
description: 'Action which bumps version of Cloudshelf repos according to semver'
inputs:
  release_type:
    description: 'The type of release. One of: production, rc, development'
    required: true
    default: 'development'
  github_token:
    description: 'GitHub repo token'
    required: true
    default: ''
  slack_channel:
    description: 'Slack Channel'
    required: false
    default: ''
  slack_token:
    description: 'slack_token'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
